version: '3'

services:
  bananaprep:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Only expose the server port
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    environment:
      - NODE_ENV=development
    restart: unless-stopped